FROM java:8
EXPOSE 8082
ADD /target/music-information-service-0.0.1-SNAPSHOT.jar music-information-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "music-information-service-0.0.1-SNAPSHOT.jar"]